package modelo;

public enum Nacionalidade {
	
	Antígua_e_Barbuda("Antiguano"), 
	Argentina("Argentino"), 
	Bahamas("Bahamense"), 
	Barbados_Barbadiano("barbadense"),
	Belize("Belizenho"), 
	Bolívia("Boliviano"), 
	Brasil("Brasileiro"), 
	Chile("Chileno"), 
	Colômbia("Colombiano"),
	Costa_Rica("Costarriquenho"), 
	Cuba("Cubano"), 
	Dominica("Dominicano"), 
	Equador("Equatoriano"), 
	El_Salvador("Salvadorenho"),
	Granada("Granadino"), 
	Guatemala("Guatemalteco"), 
	Guiana("Guianês"),
	Guiana_Francesa("Guianense"),
	Haiti("Haitiano"),
	Honduras("Hondurenho"),
	Jamaica("Jamaicano"),
	México("Mexicano") ,
	Nicarágua("Nicaraguense") ,
	Panamá("Panamenho"),
	Paraguai("Paraguaio") ,
	Peru("Peruano"),
	Porto_Rico("Portorriquenho"),
	República_Dominicana("Dominicana"),
	São_Cristóvão_e_Nevis("São-cristovense"),
	São_Vicente_e_Granadinas("São-vicentino"), 
	Santa_Lúcia("Santa-lucense"),
	Suriname("Surinamês"),
	Trinidad_e_Tobago("Trindadense"),
	Uruguai("Uruguaio"),
	Venezuela("Venezuelano"),
	Alemanha("Alemão"),
	Áustria("Austríaco"),
	Bélgica("Belga"),
	Croácia("Croata"),
	Dinamarca("Dinamarquês"),
	Eslováquia("Eslovaco"),
	Eslovênia("Esloveno"),
	Espanha("Espanhol"),
	França("Francês"),
	Grécia("Grego"),
	Hungria("Húngaro"),
	Irlanda("Irlandês"),
	Itália("Italiano"),
	Noruega("Noruego") ,
	Países_Baixos("Holandês") ,
	Polônia("Polonês"),
	Portugal("Português"),
	Reino_Unido("Britânico") ,
	Inglaterra("Inglês"),
	País_de_Gales("Galês"),
	Escócia("Escocês"),
	Romênia("Romeno"),
	Rússia("Russo"),
	Sérvio("Sérvio"),
	Suécia("Sueco"),
	Suíça("Suíço"),
	Turquia("Turco"),
	Ucrânia("Ucraniano"),
	Estados_Unidos("Americano"),
	Canadá("Canadense"),
	Angola("Angolano"),
	Moçambique("Moçambicano"),
	África_do_Sul("Sul-africano"),
	Zimbabue("Zimbabuense"),
	Argélia("Argélia"),
	Comores("Comorense"),
	Egito("Egípcio"),
	Líbia("Líbio") ,
	Marrocos("Marroquino"),
	Gana("Ganés"),
	Quênia("Queniano"),
	Ruanda("Ruandês"),
	Uganda("Ugandense"),
	Botsuana("Bechuano"),
	Costa_do_Marfim("Marfinense") ,
	Camarões("Camaronense") ,
	Nigéria("Nigeriano") ,
	Somália("Somali"),
	Austrália("Australiano") ,
	Nova_Zelândia("Neozelandês"),
	Afeganistão("Afegão"),
	Arábia_Saudita("Saudita"),
	Armênia("Armeno"),
	Armeno("Bangladesh"),
	China("Chinês"),
	Coréia_do_Norte("Norte-coreano"),
	Coréia_do_Sul("Sul-coreano"),
	Índia("Indiano"),
	Indonésia("Indonésio"),
	Iraque("Iraquiano"),
	Irã("Iraniano"),
	Israel("Israelita"),
	Japão("Japonês"),
	Malásia("Malaio"),
	Nepal("Nepalês"),
	Omã("Omanense"),
	Paquistão("Paquistanês"),
	Palestina("Palestino"),
	Qatar("Qatarense"),
	Síria("Sírio"),
	Sri_Lanka("Cingalês"),
	Tailândia("Tailandês"),
	Timor_Leste("Timorense"),
	Emirados_Árabes_Unidos("Árabe"),
	Vietnã("Vietnamita"), 
	Iêmen("Iemenita");
	
	private String descricao;
	
	Nacionalidade(String descricao) {
		this.descricao = descricao;
	}

	public String getDescricao() {
		return descricao;
	}

}
